### ISSUE TITLE
Only NaNs produced

### ISSUE THREAD

**Issue by dgenio** [twolodzko/extraDistr#1]
I'm using rmvhyper and my vector n have a length of 8614 and is consisted of one entry with 5000073631and the remaining are just one... When I sample 5e+06 I get 
Warning message:
In cpp_rmvhyper(nn, n, k) : NaNs produced

**Comment by twolodzko** [comment]
Could you provide a reproducible code example? Unfortunately it is not totally clear for me what the problem could be about. In general, `NaNs` are returned if you provide invalid parameter values, e.g. in this case `k > sum(n)` etc.
