### ISSUE TITLE
zinb gives NAs when size is non-integer

### ISSUE THREAD

**Issue by gvnmzz** [twolodzko/extraDistr#12]
rzinb samples NAs when the size parameter is non-integer.
In the documentation, it states that, how you expect from rnbinom, the size should be > 0 but need not be integer.
```{r code}
sz <- seq(0.5,5.5,0.5)
rzinb(n = sz, size = sz, prob = 0.5, pi = 0)
## [1] NA  0 NA  0 NA  3 NA  2 NA  6 NA
```

With the same paramegers, the rnbinom works fine
```{r code 2}
rnbinom(n = sz, size = sz, prob = 0.5)
## [1] 1 0 1 2 3 6 0 3 8 5 3
```

It seems that within `rng_zinb` it throws a warning if the size parameter is non-integer, and automatically returns `NA_REAL`, while the `R::rnbinom` function would otherwise work fine also with non-integer size parameter.

**Comment by twolodzko** [comment]
The number of successes is integer-valued. Counts cannot be fractional.
