### ISSUE TITLE
ZIP probability density function definition inconsistent

### ISSUE THREAD

**Issue by PDiracDelta** [twolodzko/extraDistr#15]
The [documentation](https://rdrr.io/cran/extraDistr/man/ZIP.html) states that the pdf is:

> `f(x) = [if x = 0:] (1-π)+π * exp(-λ) [else:] (1-π) * dpois(x, lambda)`

Which is not self-inconsistent, because in the first case the exponential has a factor `π` and in the second case it has a factor `(1-π)`. I assume it should have a factor `(1-π)` in both cases and it got swapped by accident with the `π` term in the first case. So I think the pdf should be:

> `f(x) = [if x = 0:] π + (1-π) * exp(-λ) [else:] (1-π) * dpois(x, lambda)`

I **think** this is just wrong in the documentation and not in the code, as I am getting sensible numbers from the `dnorm`.

**Comment by twolodzko** [comment]
Thanks, I checked the code and it is just a mistake in the docs.
