### ISSUE TITLE
pbbinom(): vectorised evaluation fails for certain combinations of values

### ISSUE THREAD

**Issue by famuvie** [twolodzko/extraDistr#16]
The following reproducible example shows that I can evaluate the cumulative probability for individual values, but putting the same values into vectors fail.

``` r
library(extraDistr)

test_dat <- 
  data.frame(
    q = c(1, 10, 10, 100),
    size = c(10, 100, 1000, 1000),
    alpha = 1, 
    beta = 1
  )

## Cumulative probabilites computed individually
test_dat$cumprobs <- 
  apply(test_dat, 1, function(x) pbbinom(x[1], x[2], x[3], x[4]))

## Cumulative probs computed with vectors

## First three rows: ok
with(
  head(test_dat, 3),
  identical(
    pbbinom(q, size, 1, 1),
    cumprobs
  )
)
#> [1] TRUE

## Last three rows: ok
with(
  tail(test_dat, 3),
  identical(
    pbbinom(q, size, 1, 1),
    cumprobs
  )
)
#> [1] TRUE

## But all four rows not ok
with(
  test_dat,
  pbbinom(q, size, 1, 1)
) # inadmissible values
#> Error in cpp_pbbinom(q, size, alpha, beta, lower.tail[1L], log.p[1L]): inadmissible values

## Not a matter of number of rows, but of combination of values:
with(
  test_dat[c(1, 4),],
  pbbinom(q, size, 1, 1)
) # inadmissible values
#> Error in cpp_pbbinom(q, size, alpha, beta, lower.tail[1L], log.p[1L]): inadmissible values
```

<sup>Created on 2018-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The problem seems to arise when the range of values is large, which makes me think of some numerical issue. But I was using the function for evaluating MCMC samples, and the ranges of values is naturally large.

**Comment by twolodzko** [comment]
Thanks, will look at it. This is not a numerical issue, it is some kind of issue with the part of code used for vectorization.

**Comment by twolodzko** [comment]
Thanks, will look at it. This is not a numerical issue, it is some kind of issue with the part of code used for vectorization.

**Comment by twolodzko** [comment]
Thanks, will look at it. This is not a numerical issue, but the part of code reliable for vectorization fails. If possible, use non-vectorized form of this function until fixed.

**Comment by twolodzko** [comment]
@famuvie Latest commit fixes the issue you described. I still need to test it further, but you could download the recent GitHub version and it should work fine. What could happen, is you can see some other error messages, but there should not be problems with the results if no error appears.
