### ISSUE TITLE
consider adding the lkj correlation distribution

### ISSUE THREAD

**Issue by bnicenboim** [twolodzko/extraDistr#20]
Hi, I'm a big fan of the package, maybe you want to consider adding the lkj correlation distribution

The code in R for dlkj and rlkj provided in https://www.rdocumentation.org/packages/rethinking/versions/1.59/topics/dlkjcorr is quite straightforward. But I don't know anything about C++.

**Comment by twolodzko** [comment]
@bnicenboim thanks, but I don't think I'll do that for two reasons:
- currently I'm just maintaining the package, I'm not considering extending it further,
- with exception of Dirichlet, it doesn't implement multivariate distributions,
- LKJ is not that straightforward, would need introducing matrix algebra libraries as dependencies etc., what I'd like to avoid if not necessary.

Also bear in mind that that it'd be hard (impossible?) to vectorize, so re-writing it to C++ probably would not give any speedup.
