### ISSUE TITLE
doubt in ddnorm 

### ISSUE THREAD

**Issue by veena12256** [twolodzko/extraDistr#22]
how to draw the curve of ddnorm (discrete normal) in R

**Comment by twolodzko** [comment]
For plotting discrete distributions, the best kind of plot is something this (from [Wolfram's documentation](https://reference.wolfram.com/language/ref/DiscretePlot.html))

![](https://reference.wolfram.com/language/ref/Files/DiscretePlot.en/O_3.png)

or this (from [Wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution))

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Poisson_pmf.svg/325px-Poisson_pmf.svg.png)

If looking for help with code, you can try [some of those resources](https://stats.meta.stackexchange.com/a/795/35989).

**Comment by veena12256** [comment]
Thank you @twolodzko .  I have one more doubt regarding the fitting of discrete distributions.  when I am trying to fit the discrete distribution on the histogram using curves, it comes perfect but it doesnt when I use lines. do you have any idea why it happens like that.

**Comment by twolodzko** [comment]
@veena12256 you should try one of the R help forums, or StackOverflow.com, this doesn't seem to be related to this package.
