### ISSUE TITLE
CRAN warnings

### ISSUE THREAD

**Issue by twolodzko** [twolodzko/extraDistr#29]
e-mail from CRAN:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_extraDistr.html>.
>
> Please correct before 2023-12-12 to safely retain your package on CRAN.

**Comment by twolodzko** [comment]
Fixed by #31 thanks to @eddelbuettel

**Comment by eddelbuettel** [comment]
I noticed two more nags, one of which you seem to have taken care of (no longer forcing / setting) CXX_STD.  The other is the LazyData so consider this maybe too:

```diff
@@ -27,10 +27,8 @@ License: GPL-2
 URL: https://github.com/twolodzko/extraDistr
 BugReports: https://github.com/twolodzko/extraDistr/issues
 Encoding: UTF-8
-LazyData: TRUE
 Depends: R (>= 3.1.0)
 LinkingTo: Rcpp
 Imports: Rcpp
 Suggests: testthat, LaplacesDemon, VGAM, evd, skellam, triangle, actuar
-SystemRequirements: C++
 RoxygenNote: 7.2.3
```

You don't need to declare C++ as being used, files in `src/` ending in `.cc` or `.cpp` do that.

**Comment by twolodzko** [comment]
Thanks, will keep it in mind for the future.

**Comment by eddelbuettel** [comment]
Turns our @Bisaloo already sent you a commit on `LazyData` so all good and the `SystemRequirements: C++` is just cosmetic and triggers no issue so you are all set!
