### ISSUE TITLE
Cannot submit to CRAN

### ISSUE THREAD

**Issue by twolodzko** [twolodzko/extraDistr#30]
I cannot submit v 1.10.0 to CRAN because their checks throw:

> Undocumented code objects:
>   'dbbinom' 'dbern' 'dbetapr' 'dbhatt' 'dbnbinom' 'dbvnorm' 'dbvpois'
>   'dcat' 'ddgamma' 'ddirichlet' 'ddirmnom' 'ddlaplace' 'ddnorm'
>   'ddunif' 'ddweibull' 'dfatigue' 'dfrechet' 'dgev' 'dgompertz' 'dgpd'
>   'dgpois' 'dgumbel' 'dhcauchy' 'dhnorm' 'dht' 'dhuber' 'dinvchisq'
>   'dinvgamma' 'dkumar' 'dlaplace' 'dlgser' 'dlomax' 'dlst' 'dmixnorm'
>   'dmixpois' 'dmnom' 'dmvhyper' 'dnhyper' 'dnsbeta' 'dpareto' 'dpower'
>   'dprop' 'drayleigh' 'dsgomp' 'dskellam' 'dslash' 'dtbinom' 'dtnorm'
>   'dtpois' 'dtriang' 'dwald' 'dzib' 'dzinb' 'dzip' 'pbbinom' 'pbern'
>   'pbetapr' 'pbhatt' 'pbnbinom' 'pcat' 'pdgamma' 'pdlaplace' 'pdnorm'
>   'pdunif' 'pdweibull' 'pfatigue' 'pfrechet' 'pgev' 'pgompertz' 'pgpd'
>   'pgpois' 'pgumbel' 'phcauchy' 'phnorm' 'pht' 'phuber' 'pinvchisq'
>   'pinvgamma' 'pkumar' 'plaplace' 'plgser' 'plomax' 'plst' 'pmixnorm'
>   'pmixpois' 'pnhyper' 'pnsbeta' 'ppareto' 'ppower' 'pprop' 'prayleigh'
>   'psgomp' 'pslash' 'ptbinom' 'ptnorm' 'ptpois' 'ptriang' 'pwald'
>   'pzib' 'pzinb' 'pzip' 'qbern' 'qbetapr' 'qcat' 'qdunif' 'qdweibull'
>   'qfatigue' 'qfrechet' 'qgev' 'qgompertz' 'qgpd' 'qgumbel' 'qhcauchy'
>   'qhnorm' 'qht' 'qhuber' 'qinvchisq' 'qinvgamma' 'qkumar' 'qlaplace'
>   'qlgser' 'qlomax' 'qlst' 'qnhyper' 'qnsbeta' 'qpareto' 'qpower'
>   'qprop' 'qrayleigh' 'qtbinom' 'qtlambda' 'qtnorm' 'qtpois' 'qtriang'
>   'qzib' 'qzinb' 'qzip' 'rbbinom' 'rbern' 'rbetapr' 'rbhatt' 'rbnbinom'
>   'rbvnorm' 'rbvpois' 'rcat' 'rcatlp' 'rdgamma' 'rdirichlet' 'rdirmnom'
>   'rdlaplace' 'rdnorm' 'rdunif' 'rdweibull' 'rfatigue' 'rfrechet'
>   'rgev' 'rgompertz' 'rgpd' 'rgpois' 'rgumbel' 'rhcauchy' 'rhnorm'
>   'rht' 'rhuber' 'rinvchisq' 'rinvgamma' 'rkumar' 'rlaplace' 'rlgser'
>   'rlomax' 'rlst' 'rmixnorm' 'rmixpois' 'rmnom' 'rmvhyper' 'rnhyper'
>   'rnsbeta' 'rpareto' 'rpower' 'rprop' 'rrayleigh' 'rsgomp' 'rsign'
>   'rskellam' 'rslash' 'rtbinom' 'rtlambda' 'rtnorm' 'rtpois' 'rtriang'
>   'rwald' 'rzib' 'rzinb' 'rzip'

Which doesn't seem to be true, but I have no idea how to "fix" it for now.

**Comment by dill** [comment]
(Saw your post on Mastodon. Apologies if the below is something you've already thought about.)

I was able to replicate this error on my machine (Debian 12, Intel) when cloning the repo and running `R CMD check extraDistr`. Using `devtools::document()` to create the entries in `man/` removed this problem (and generated the corresponding entries).

I don't think (though I've not maintained a package on CRAN for a couple of years now)  that CRAN will generate documentation on the fly, so is there a chance that the `man/` directory was not populated prior to submission?

**Comment by twolodzko** [comment]
Thanks for the hint @dill. I checked it manually when submitting, but maybe I missed something or did something wrong. I'll double-check on the next submit.

**Comment by dill** [comment]
Happy to test out your submission on my machine if that helps! :)
